package enhancedbiomes.world.biomestats;

import static enhancedbiomes.world.biome.EnhancedBiomesArchipelago.*;
import static enhancedbiomes.world.biome.EnhancedBiomesBiome.*;
import static enhancedbiomes.world.biome.EnhancedBiomesGrass.*;
import static enhancedbiomes.world.biome.EnhancedBiomesPlains.*;
import static enhancedbiomes.world.biome.EnhancedBiomesRock.*;
import static enhancedbiomes.world.biome.EnhancedBiomesSand.*;
import static enhancedbiomes.world.biome.EnhancedBiomesSandstone.*;
import static enhancedbiomes.world.biome.EnhancedBiomesSnow.*;
import static enhancedbiomes.world.biome.EnhancedBiomesTropical.*;
import static enhancedbiomes.world.biome.EnhancedBiomesWetland.*;
import static enhancedbiomes.world.biome.EnhancedBiomesWoodland.*;
import static net.minecraft.world.biome.BiomeGenBase.*;
import static net.minecraftforge.common.BiomeDictionary.*;
import static net.minecraftforge.common.BiomeDictionary.Type.*;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraftforge.common.BiomeDictionary;
import net.minecraftforge.common.BiomeDictionary.Type;

public class BiomeTypes {
	public static void registerAllBiomeTypes() {
    	registerBiomeType(biomeMountainArchipelago, 	OCEAN, MOUNTAIN, HILLS);
		registerBiomeType(biomeDesertArchipelago, 		OCEAN, DRY, SANDY);
		registerBiomeType(biomeForestArchipelago, 		OCEAN, FOREST);
		registerBiomeType(biomeJungleArchipelago, 		OCEAN, HOT, WET, DENSE, JUNGLE);	
		registerBiomeType(biomePineArchipelago, 		OCEAN, COLD, CONIFEROUS, FOREST);	
		registerBiomeType(biomeSnowArchipelago, 		OCEAN, COLD, SNOWY, WASTELAND);	
		registerBiomeType(biomePlainsArchipelago, 		OCEAN, PLAINS);	
		registerBiomeType(biomeBadlands, 				HOT, DRY, SPARSE, WASTELAND);
		registerBiomeType(biomePlateau, 				MOUNTAIN, HILLS);
		registerBiomeType(biomeMountains, 				MOUNTAIN);
		registerBiomeType(biomeMountainsEdge, 			MOUNTAIN, HILLS);
		registerBiomeType(biomeMountainTundra, 			MOUNTAIN, COLD);
		registerBiomeType(biomeGrasslands, 				PLAINS); 	  
		registerBiomeType(biomeSavannah, 				HOT, SAVANNA, PLAINS, SPARSE);	  	  
		registerBiomeType(biomeSteppe, 					COLD, WET, PLAINS);	
		registerBiomeType(biomePrairie, 				HOT, PLAINS, SPARSE);
		registerBiomeType(biomeLowHills, 				PLAINS);
		registerBiomeType(biomeMeadow, 					PLAINS);
		registerBiomeType(biomeGrasslandsRoofed, 		PLAINS, FOREST);  	
		registerBiomeType(biomeMeadowM, 				PLAINS);
		registerBiomeType(biomeRockyDesert, 			HOT, DRY, SANDY, WASTELAND);  	  
		registerBiomeType(biomeScrub, 					HOT, DRY, SANDY, SPARSE);
		registerBiomeType(biomeSahara, 					HOT, DRY, SANDY); 	  
		registerBiomeType(biomeAlpine, 					COLD, MOUNTAIN, SNOWY, CONIFEROUS);		  
		registerBiomeType(biomeGlacier, 				COLD, MOUNTAIN);
		registerBiomeType(biomeTundra, 					COLD, SNOWY);
		registerBiomeType(biomePlateauSnow, 			COLD, SNOWY, MOUNTAIN, HILLS);
		registerBiomeType(biomeSnowDesert, 				COLD, SNOWY, SANDY);							
		registerBiomeType(biomePolarDesert, 			COLD, SNOWY, WASTELAND);  																				
		registerBiomeType(biomeSnowyRanges, 			COLD, MOUNTAIN, HILLS, SNOWY, FOREST);
		registerBiomeType(biomeVolcano, 				NETHER, WASTELAND);
		registerBiomeType(biomeWasteLands, 				DRY, WASTELAND);																				
		registerBiomeType(biomeRockHills, 				WASTELAND, MOUNTAIN);
		registerBiomeType(biomeBasin, 					WASTELAND);
		registerBiomeType(biomeStoneCanyon, 			WASTELAND, HILLS);
		registerBiomeType(biomeSandStoneRanges, 		HOT, SANDY, MESA, HILLS, SPARSE);
		registerBiomeType(biomeScree, 					HOT, SANDY, MESA, SPARSE);
		registerBiomeType(biomeSandStoneCanyon, 		HOT, MESA, DRY);
		registerBiomeType(biomeClayHills, 				HOT, MESA);
		registerBiomeType(biomeCreekBed, 				HOT, SPARSE);
		registerBiomeType(biomeSandStoneRangesM, 		HOT, SANDY, MESA, HILLS, SPARSE);
		registerBiomeType(biomeMangrove, 				WET, SWAMP);
		registerBiomeType(biomeEphemeralLake, 			WET, SWAMP, BEACH);
		registerBiomeType(biomeEphemeralLakeEdge, 		WET, SWAMP, BEACH);
		registerBiomeType(biomeFen, 					WET, SWAMP);	
		registerBiomeType(biomeCarr, 					WET, SWAMP, FOREST);	
		registerBiomeType(biomeLake, 					WET, SWAMP);		
		registerBiomeType(biomeWoodlandLake, 			WET, SWAMP, FOREST);	
		registerBiomeType(biomeWoodlandLakeEdge, 		WET, SWAMP, FOREST);	
		registerBiomeType(biomeMarsh, 					WET, SWAMP);			
		registerBiomeType(biomeBlossomWoods, 			FOREST);
		registerBiomeType(biomeBlossomHills, 			FOREST, HILLS);
		registerBiomeType(biomeWoodLands, 				FOREST);	 		  
		registerBiomeType(biomeWoodLandHills, 			FOREST, HILLS);
		registerBiomeType(biomePineForest, 				COLD, CONIFEROUS, FOREST, SNOWY);
		registerBiomeType(biomeOakForest, 				FOREST);
		registerBiomeType(biomeKakadu, 					HOT, JUNGLE);		  	  
		registerBiomeType(biomeSilverPineForest, 		CONIFEROUS, FOREST);
		registerBiomeType(biomeSilverPineHills, 		CONIFEROUS, FOREST, HILLS);
		registerBiomeType(biomeAspenForest, 			COLD, FOREST);
		registerBiomeType(biomeAspenHills, 				COLD, FOREST, HILLS);
		registerBiomeType(biomeCypressForest, 			COLD, CONIFEROUS, FOREST);
		registerBiomeType(biomeShield, 					COLD, CONIFEROUS, FOREST);
		registerBiomeType(biomeForestMountains, 		FOREST, MOUNTAIN);
		registerBiomeType(biomeWoodlandField, 			PLAINS);  	  
		registerBiomeType(biomeCypressPlateau, 			COLD, CONIFEROUS, FOREST, HILLS);		
		registerBiomeType(biomeAlpineEdge, 				COLD, CONIFEROUS, FOREST, HILLS);
		registerBiomeType(biomeFirForest, 				COLD, CONIFEROUS, FOREST, SNOWY);	
		registerBiomeType(biomeOasis, 					WET, SWAMP, JUNGLE);
		registerBiomeType(biomeRainforest,				WET, HOT, JUNGLE, DENSE);		  	  
		registerBiomeType(biomeRainforestValley, 		WET, HOT, JUNGLE, DENSE, SWAMP);
		registerBiomeType(biomeXericShrubland,			HOT, DRY, SANDY, SPARSE);
		registerBiomeType(biomeDrifts,					COLD, SNOWY, CONIFEROUS);
	}
}
